CREATE WAREHOUSE AG_MAVEN_POWER_BI
WITH WAREHOUSE_SIZE = 'SMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE; 

CREATE DATABASE AG_POWERBI_CHALLENGE_1;
USE AG_POWERBI_CHALLENGE_1;


CREATE OR REPLACE TABLE MAVEN_VITAL_TABLE(
order_details_id INTEGER,
order_id INTEGER,
pizza_id VARCHAR(50),
quantity INTEGER);

SELECT * FROM MAVEN_VITAL_TABLE;


CREATE OR REPLACE TABLE MAVEN_TABLE_PIZZAS(
pizza_id VARCHAR(50),
pizza_type_id VARCHAR(50),
size CHAR(5),
price NUMBER(4,2));

SELECT * FROM MAVEN_TABLE_PIZZAS;



------------------Joining of the Table------------------------------------------
CREATE OR REPLACE TABLE NEW_VITAL_TABLE AS 
SELECT V.order_details_id AS ORDER_DETAIL_ID,V.order_id AS ORDER_ID,V.pizza_id AS VITAL_PIZZA_ID,V.quantity AS QUANTITY,P.pizza_id AS PIZZA_ID,
P.pizza_type_id AS PIZZA_TYPE,P.size AS PIZZA_SIZE,P.price AS PIZZA_PRICE
FROM MAVEN_VITAL_TABLE V
LEFT OUTER JOIN 
MAVEN_TABLE_PIZZAS P ON V.pizza_id = P.pizza_id ;

SELECT * FROM NEW_VITAL_TABLE;


SELECT SUM(PIZZA_PRICE * QUANTITY) FROM NEW_VITAL_TABLE;